### ISSUE TITLE
[Request] Adding single key press

### ISSUE THREAD

**Issue by Yot360** [Madsycode/book-fuse-engine#3]
How would it be possible to add a single key press check on the Flappy Plane demo game?
For example, you wouldn't be able to fly by keeping the key pressed, but it would do more of a "jump" where you need to release the key to jump again, like the original flappy bird. I can't find the right way to do this, but it would be a cool feature.

**Comment by Madsycode** [comment]
Hi you can simpe use a state machine! where you have a variable that is set to true or false as long as the key is pressed! you can use the event system to achieve that! in the on_pressed() callback you check the key and set the state to whatever yyou want and in the on_release you reset!
