### ISSUE TITLE
2 Temporary objects for every entity per system!

### ISSUE THREAD

**Issue by JG-Adams** [Madsycode/book-fuse-engine#6]
Have a look at engine/src/ecs/system.h

this function is used per frame for every system that is implemented:
    template<typename T> 
    FUSE_INLINE auto view() {
      std::vector<entity> entities;
      for(auto& e : _registry->view<T>()) {
        entities.push_back(entity(e, _registry));
      }
      return entities;
    }

Just put FUSE_INFO("object created"); next to push_back and you'll discover that there is allocation/ deallocation of every entity just to return it.
It also happens inside _registry->view<T> allocating a list.

This is not a good thing because it defeat the purpose of ECS for cache friendliness and it's really a terrible things to try and scale your project with it.
I don't know how much of an impact this would have. But, it is certainly huge.
Breaking cache flow is a hundred time slower on it's own. We're allocating two object per objects per 

There got to be a solution to this.

**Comment by JG-Adams** [comment]
Well, I made my own ECS.
If it wasn't for your tutorial it would have been much more difficult. :)

**Comment by Madsycode** [comment]
Great!!!:) am happy to be part of your journey!! keep going you have what it takes!
